Repository palantir/conjure-go-runtime, pull requests merged in 2021-02, with the labels that each got.

#146 Make runtime URIs reloadable
  conjure-go-client/httpclient/client.go
  conjure-go-client/httpclient/client_builder.go
  conjure-go-client/httpclient/client_params.go
  conjure-go-client/httpclient/client_params_test.go
  go.mod
  go.sum
  vendor/github.com/palantir/pkg/refreshable/refreshable_types.go
  vendor/modules.txt
Labels: merge when ready

#147 Add WithUnlimitedRetries client param
  changelog/@unreleased/pr-147.v2.yml
  conjure-go-client/httpclient/client_builder.go
  conjure-go-client/httpclient/client_params.go
  conjure-go-client/httpclient/client_params_test.go
Labels: autorelease, merge when ready

#152 Replace internal usage of "retries" with "attempts"
  conjure-go-client/httpclient/client.go
  conjure-go-client/httpclient/client_builder.go
  conjure-go-client/httpclient/client_params.go
  conjure-go-client/httpclient/client_params_test.go
  conjure-go-client/httpclient/internal/request_retrier.go
  conjure-go-client/httpclient/internal/request_retrier_test.go
Labels: merge when ready, no changelog

#153 Fix request retrier to handle zero retry cases
  changelog/@unreleased/pr-153.v2.yml
  conjure-go-client/httpclient/client_params.go
  conjure-go-client/httpclient/internal/request_retrier.go
  conjure-go-client/httpclient/internal/request_retrier_test.go
Labels: merge when ready

#154 Fix request retrier to handle unlimited retries
  changelog/@unreleased/pr-154.v2.yml
  conjure-go-client/httpclient/internal/request_retrier.go
  conjure-go-client/httpclient/internal/request_retrier_test.go
Labels: merge when ready
