Repository palantir/conjure-go-runtime, pull requests merged in 2025-01, with the labels that each got.

#739 fix: Prepend request modifiers with WithInnerMiddleware() to execute in the intuitive order
  changelog/@unreleased/pr-739.v2.yml
  conjure-go-client/httpclient/authn_test.go
  conjure-go-client/httpclient/body_handler_test.go
  conjure-go-client/httpclient/client.go
  conjure-go-client/httpclient/client_params.go
  conjure-go-client/httpclient/client_params_test.go
  conjure-go-client/httpclient/metrics_test.go
Labels: merge when ready

#738 Replace joinURIAndPath with url.URL.JoinPath
  conjure-go-client/httpclient/client.go
  conjure-go-client/httpclient/client_path_test.go
Labels: no changelog, merge when ready

#749 Partially Revert "fix: Prepend request modifiers with WithInnerMiddleware() to execute in the intuitive order (#739)"
  changelog/@unreleased/pr-749.v2.yml
  conjure-go-client/httpclient/authn_test.go
  conjure-go-client/httpclient/client.go
  conjure-go-client/httpclient/client_params_test.go
Labels: autorelease

#748 Add YAML Codecs
  conjure-go-contract/codecs/yaml.go
  conjure-go-contract/codecs/yaml_test.go
Labels: merge when ready, autorelease
